# Generated by Django 6.0.6 on 2026-06-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='is_active',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
